src/culinary_post/urls.py
from django.urls import path
from . import views

app_name = 'culinary_post'

urlpatterns = [
    path('', views.post__list_view, name='culinary_post_view'),
    path('detail/<int:pk>', views.CulinaryPostDetailView.as_view(), name='culinary_post_detail_view'),
    path("detail/<int:pk>/<int:number>/", views.CulinaryPostDetailView.as_view(), name='load_more_comments'),
    path('post/add_comment/<int:pk>', views.AddCommentToPost.as_view(), name='post_add_comment'),
    path('post_add/', views.posts_add, name='culinary_post_add'),
    path('liked/', views.like_unlike_post, name='like_post_view'),
    path('delete/<pk>/delete/', views.CulinaryPostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', views.CulinaryPostUpdateView.as_view(), name='post_update'),
]

src/culinary_post/templates/culinary_post/culinary_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Кулинарные посты
{% endblock title %}

{% block breadcrumbs %}
<i class="right chevron icon divider black"></i>
<span class="active section" >Кулинарные посты</span>
{% endblock breadcrumbs %}
{% block content %}
<h2>Кулинарные посты</h2>
<div class="ui stackable grid m-2">

        {% for post in qs %}
        <div class="eight wide column">
        <div class="ui fluid card">
            <div class="content">
                <div class="ui right floated meta">
                    <div class="ui grid">
                        <div class="ui inline row">
                            {% ifequal request.user post.author.user %}
                            <div class="ui row">
                                <a href="{% url 'culinary_post:post_update' post.pk %}">
                                    <small>Обновить</small>
                                </a>
                                <a href="{% url 'culinary_post:post_delete' post.pk %}">
                                    <small>Удалить</small>
                                </a>

                            </div>
                            {% endifequal %}
                        </div>
                    </div>
                </div>
                {% ifequal request.user post.author.user %}

                <small>{{ post.created|timesince}} назад</small>
                {% else %}
                <img loading="lazy" src="{{ post.author.avatar.url }}" class="ui avatar url">
                <small>{{ post.author.user.username }} - {{ post.created|timesince}} назад</small>
                {% endifequal %}

                <div class="ui fluid image">
                    {% if post.image %}
                    <img loading="lazy" src="{{ post.image.url }}">
                    {% endif %}
                </div>

            </div>
            <div class="content">
                <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
            </div>
            <div class="extra content">
                <i class="comment icon"></i>
                <small>{{ post.get_total_comments }}</small>
            </div>
        </div>
            </div>
        {% endfor %}

</div>
{% endblock content %}

src/culinary_post/templates/culinary_post/post_delete.html
{% extends 'base.html' %}

{% block title %}Удалить пост {% endblock title %}

{% block robots %}
<meta name="robots" content="noindex">
{% endblock robots %}

{% block content %}

{% if messages %}
{% for message in messages %}

<div class="ui negative message mt-2">
    <div class="header">
        {{ message }}
    </div>
</div>

{% endfor %}
{% endif %}

{% if not messages %}
<div class="ui segment mt-2">
    <h3>Удалить пост?</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p>Вы уверены что хотите удалить пост?</p>
        <button type="submit" class="ui button negative">Удалить</button>
    </form>
</div>
{% endif %}

{% endblock content %}

src/culinary_post/templates/culinary_post/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}
{% load hitcount_tags %}

{% block title %}У-шефа {{ post.title }}{% endblock title %}

    {% block meta_description %}
        <meta name="description" content="У-шефа пост {{ post.title }}"  itemprop="description">
    {% endblock meta_description %}

{% block breadcrumbs %}
<i class="right chevron icon divider black"></i>
<a class="section navbar_links_yummy black" href="{% url 'culinary_post:culinary_post_view' %}">Кулинарные посты</a>
<i class="right chevron icon divider black"></i>
<span class="active section">{{post.title}}</span>
{% endblock breadcrumbs %}


{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="ui info message">
        <i class="close icon"></i>
        <div class="header">
            {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}
<div class="dish_detail">
    <div class="ui two right aligned column grid mx-10">
        <div class="right floated middle aligned eight wide column">
            <small>{{ post.created }}/{{ post.user }}</small>
            <img loading="lazy" class="ui avatar image"
                src="{% if post.user.profile.avatar %}{{ post.user.profile.avatar.url }}{% else %}{% static '/image/avatar_man.png' %}{% endif %}">
        </div>
    </div>
    <div class="dish_row">
        <h1 class="font-lobster p-10">{{ post.title }}</h1>
    </div>

    <div class="row">
        <img loading="lazy" class="ui fluid rounded image" src="{{ post.image.url }}" alt="{{ post.title }}">
    </div>
    <div class="row">
        <p class="font-oswald p-10">{{post.content|safe}}</p>
    </div>

    <div class="ui equal width grid p-10">
        <div class="equal width row">
            <div class="column">
                <div class="ui grid p-10">
                    <div class="inline column row">
                        {% get_hit_count for post as count %}
                        <i class="ui eye big yellow icon main_point" aria-hidden="true"></i><small
                            class="mr-5 font-s-20 c-black">{{count}}</small>
                        <a href="#dishComments">
                            <i class='ui comment outline big yellow icon main_point'></i><small
                                class="mr-5 font-s-20 c-black">
                                {{ post.get_total_comments}}</small>
                        </a>

                        <div class="right floated">
                            <form action="{% url 'culinary_post:like_post_view' %}" method="post" id="post_like_form">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                <i id="post_like_button" datatype="{{ post.id }}"
                                   class="ui thumbs {% if user.profile in post.liked.all %} down {% else %} up {% endif %} outline big yellow icon main_point icon"></i>
                                <small class="mr-5 font-s-20 c-black like-count">
                                    {{ post.get_total_likes }}
                                    </small>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Show comments -->
<hr>
{% if post_comments %}
<h3 id="dishComments" class="ui header">Коментарии</h3>
<button class="cmt_btn ui fluid button mb-4">Показать / Скрыть коментарии</button>
<div class="comment-box">
    <div class="comment">
        {% if comment_size > post_comments_len %}
        <div class="ui fluid button get_another_number" data-href-template="{{post.get_absolute_url }}">Открыть
            сообшения</div>
        {% endif %}
    </div>
    <div class="ui threaded comments">
        {% recursetree post_comments %}
        <div class="comment custom_comment">
            <a class="avatar" href="#">
                <img loading="lazy" src="{% if node.author.avatar %}{{ node.author.avatar.url }}{% else %}{% static '/image/avatar_man.png' %}{% endif %}"
                    alt="avatarka">
            </a>
            <div class="content">
                <a class="author" href="{{ node.author.get_user_profile_detail_absolute_url }}">{{ node.author.first_name }}</a>
                <div class="metadata">
                    <span class="date">{{ node.created }}</span>
                </div>
                <div class="text">
                    {{ node.text }}
                </div>
                {% if node.level < 2 %} <div id="{{node.id}}" class="actions">
                    <a class="ui basic mini positive button" onclick="addComment({{ node.id }})">Ответить</a>
            </div>
            {% endif %}
        </div>

        {% if not node.is_leaf_node %}
        <div class="comments">
            {{children}}
        </div>
        {% endif %}
    </div>
    {% endrecursetree %}
    </div>
</div>
{% else %}
    <h3 id="dishComments" class="ui header">Пока нет комментариев</h3>
{% endif %}
<!-- Form for reviews -->

<form action="{% url 'culinary_post:post_add_comment' post.id %}" method="post" class="ui form input_background formReview"
    id="formReview">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="ui fluid basic positive button mt-10 comment_button">ДОБАВИТЬ КОММЕНТАРИЙ</button>
</form>
{{status}}
<!-- Form for reviews -->

{% endblock content %}

{% block jscdn %}
    <!--Like and add dish to culinary book action Js cdn-->
    <script type="text/javascript" src="{% static 'js/post_detail.min.js' %}"></script>
{% endblock jscdn %}

src/culinary_post/templates/culinary_post/post_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Обновить пост
{% endblock title %}

{% block robots %}
<meta name="robots" content="noindex">
{% endblock robots %}

{% block content %}
<div class="ui segment">
    <h3>Обновить пост</h3>
    <form class="ui form" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
            {{ form.title.errors }}
            {{ form.title.label_tag }}

            <div class="{% if form.title.errors %}error{% endif %} field">
                {{ form.title }}
            </div>
            {{form.image.errors}}
            {{form.image.label_tag}}
            <div class="{% if form.image.errors %}error{% endif %} field">
                <div class="ui medium image poster_image_div ">
                    <img loading="lazy" id="poster_image_id" class="ui centered medium rounded image" src="{{ form.initial.image.url }}">
                    <div class="form__add-img"></div>
                </div>
                <input class="d_none" type="file" name="image" accept="image/*" required="" id="id_poster" onchange="readURL(this)">
            </div>
        {{form.content.errors}}
        {{form.content.label_tag}}
        <div class="{% if form.content.errors %}error{% endif %} field">
            {{form.media}}
            {{form.content}}
        </div>
        <button type="submit" class="ui fluid inverted green button mt-4">Обновить</button>
    </form>
</div>
{% endblock content %}

{% block jscdn %}
<script async type="text/javascript" src="{% static 'js/add_recipe.min.js' %}"></script>
{% endblock jscdn %}

src/culinary_post/templates/culinary_post/posts_add.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Добавить кулинарный пост {% endblock title %}

{% block robots %}
<meta name="robots" content="noindex">
{% endblock robots %}

{% block content %}
<div class="column">
    <h3 class="header">Добавить кулинарный пост</h3>
    <form action="{% url 'culinary_post:culinary_post_add' %}" method="post" class="ui form"
        enctype="multipart/form-data">
        {% csrf_token %}
            {{ p_form.errors }}
            {{ p_form.title.label_tag }}
            <div class="{% if p_form.title.errors %}error{% endif %} field">

                {{ p_form.title }}
            </div>
            {{p_form.image.label_tag}}
            <div class="{% if p_form.image.errors %}error{% endif %} field">
                <div class="ui medium image poster_image_div ">
                    <img loading="lazy" id="poster_image_id" class="ui centered medium rounded image"
                         src="{% static  '/image/empty_image.jpeg' %}">
                    <div class="form__add-img"></div>
                </div>
                <input class="d_none" type="file" name="image" accept="image/*" required="" id="id_poster"
                       onchange="readURL(this)">
                {{p_form.image.errors}}
            </div>
        {{p_form.content.errors}}
        {{p_form.content.label_tag}}
        <div class="{% if p_form.content.errors %}error{% endif %} field">
            {{p_form.media}}
            {{p_form.content}}
        </div>
        <button type="submit" class="ui fluid inverted green button mt-10">Опубликликовать</button>
    </form>
</div>
{% endblock content %}
{% block jscdn %}
<script async type="text/javascript" src="{% static 'js/add_recipe.min.js' %}"></script>
{% endblock jscdn %}