src/culinary_post/urls.py
from django.urls import path
from . import views

app_name = 'culinary_post'

urlpatterns = [
    path('', views.post__list_view, name='culinary_post_view'),
    path('detail/<int:pk>', views.CulinaryPostDetailView.as_view(), name='culinary_post_detail_view'),
    path("detail/<int:pk>/<int:number>/", views.CulinaryPostDetailView.as_view(), name='load_more_comments'),
    path('post/add_comment/<int:pk>', views.AddCommentToPost.as_view(), name='post_add_comment'),
    path('post_add/', views.posts_add, name='culinary_post_add'),
    path('liked/', views.like_unlike_post, name='like_post_view'),
    path('delete/<pk>/delete/', views.CulinaryPostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', views.CulinaryPostUpdateView.as_view(), name='post_update'),
]

src/culinary_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='text/xml')),
    path('ads.txt', TemplateView.as_view(template_name='ads.txt', content_type='text/xml')),
    path('sellers.json', TemplateView.as_view(template_name='sellers.json', content_type='text/json')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ushefa_admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('contact.urls', namespace='profile')),
    path('posts/', include('culinary_post.urls', namespace='culinary_post')),
    path('private/chat/', include('private_chat.urls', namespace='private_chat')),
    path('', include('culinary_recipe.urls', namespace='culinary_recipe')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/culinary_recipe/urls.py
from django.urls import path
from . import views


app_name = 'culinary_recipe'
urlpatterns = [
    path('', views.CategoryViewList.as_view(), name='home'),
    path('ajax/', views.get_ajax_response_category, name='get_ajax_response_category'),
    path('dishes/', views.GetItems.as_view(), name='dishes'),
    path('dishes/by_search/', views.Search.as_view(), name='search_dishes'),
    path('dishes/by_search/<int:page_num>', views.Search.as_view(), name='search_pagination'),
    path('dishes/by_search_title/', views.SearchByTitle.as_view(), name='search_dishes_by_title'),
    path('dishes/add_recipe/', views.DishCreateView.as_view(), name='add_recipe'),
    path('dishes/update_dish/<slug:slug>/', views.DishUpdateView.as_view(), name='update_meal'),
    path('dishes/delete_dish/<int:pk>/', views.DishDeleteView.as_view(), name='delete_meal'),
    path('detail/<slug:slug>/<int:pk>', views.MealDetailView.as_view(), name='detail_view'),
    path("detail/<str:slug>/<int:pk>/<int:number>/", views.MealDetailView.as_view(), name='load_more_comments'),
    path('review/<int:pk>/', views.AddCommentToDish.as_view(), name='add_review'),
    path('recipe/dishes/<slug:slug>/', views.GetItems.as_view(), name='last_list'),
    path('likes_meal/', views.like_unlike_post, name='likes_meal'),
    path('json/', views.ingredient_list_view, name='get_ingredient_lists'),
    path('category/country/<slug:country>/<int:pk>', views.GetItems.as_view(), name='by_country'),
    path('<slug:slug>/', views.get_sub_category, name='cats_list'),
]

src/templates/base.html
<!doctype html>
<html lang="ru">
{% load static %}
{% load meal_tags %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="yandex-verification" content="a8c693b16a7975eb" />

    <link rel="icon" type="image/png" sizes="32x32 120x120 | any" href="/static/image/icons_ushefa.png" />
    <link rel="mask-icon" href="/static/image/icons_ushefa.svg" color="#00а0ff">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/image/icon_header60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/image/icon_header76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/image/icon_header120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/image/icon_header144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/image/icon_header152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/image/icon_header180.png">
    <!-- Yandex.RTB -->
    <script>window.yaContextCb=window.yaContextCb||[]</script>
    <script src="https://yandex.ru/ads/system/context.js" async></script>
    <!-- Yandex.RTB -->
    <title>{% block title %}У-шефа - Лучшие кулинарные рецепты мира{% endblock title %}</title>
    <meta name="keywords" content="рецепты блюд, кулинарные рецепты, кулинария, рецепты, новые рецепты">
    {% block meta_description %}
    <meta name="description"
        content="Готовите ли вы к праздникам или просто нуждаетесь в отличных идеях на ужин, у нас есть для вас рецепты, советы по приготовлению и многое другое"
        itemprop="description">
    {% endblock meta_description %}

    {% block robots %} {% endblock robots %}
    <link media="all" rel="stylesheet" type="text/css" href="{% static 'Semantic_UI/semantic.min.css' %}">
    <link media="all" rel="stylesheet" type="text/css" href="{% static 'css/base.min.css' %}">
    {% block cdn %}

    {% endblock cdn %}

    <style>
        @font-face {
            font-family: 'Lobster';
            font-style: normal;
            font-weight: 400;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/lobster/v23/neILzCirqoswsqX9zoamM4MwWJXNqA.woff2) format('woff2');
            unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
        }

        @font-face {
            font-family: 'Oswald';
            font-style: normal;
            font-weight: 400;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/oswald/v40/TK3_WkUHHAIjg75cFRf3bXL8LICs1_FvsUJiYySUhiCXABTV.woff) format('woff');
            unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
        }
    </style>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ER9QWWWZHD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-ER9QWWWZHD');
    </script>

    <!--    Google adsens-->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5728429283871821"
     crossorigin="anonymous"></script>
    <!--    end Google adsens-->

    <!--    mail ru domane proof-->
    <meta name="mailru-domain" content="VxoDTydYgGtp85xl" />
    <!--    google search console domane proof pleas work-->
    <meta name="google-site-verification" content="8P7W4EhJuTSXjQstz-APNRDoVJIyuhaekolpPdf_yF4" />
</head>

<body class="body_yummy">
    {% include 'includes/header.html' %}
    <div class="ui small center basic test modal ushefa_modal center aligned grid">

        <i class="big white close icon"></i>
        <div class="ui header over-flow">
            <hr>
            <div class="item"><a class="p-2 navbar_links_yummy font-oswald"
                    href="{% url 'culinary_post:culinary_post_view' %}">Кулинарные посты</a></div>
            <hr>
            {% get_categories as categories_modal %}
            <div class="ui inverted accordion">
                {% for category in categories_modal %}
                {% if category.sub_category.all %}
                <div class="title">
                    <i class="dropdown icon"></i>
                    <a href="{{ category.get_absolute_url }}" class="navbar_links_yummy font-oswald font-oswald">
                        {{ category.name }}
                    </a>
                </div>

                <div class="middle aligned content" id="{{ category.slug }}">
                    {% for sub_category in category.sub_category.all %}
                    <p class="accordion transition visible" style="display: block !important;">
                        <a href="{{ sub_category.get_absolute_url }}" class="navbar_links_yummy font-oswald pl-20">
                            {{sub_category.name}}
                        </a>
                    </p>
                    {% endfor %}
                </div>
                {% else %}
                <a href="{{ category.get_absolute_url }}" class="navbar_links_yummy font-oswald pl-10">
                    {{ category.name }}
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Content side -->
    <div class=" ui bread " style="">
        <div class="custom_container">
            {% block steps_breadcrumbs %}
            <div class="mt-2">
                <div class="ui breadcrumb font-oswald black p-10">

                    <a class="section navbar_links_yummy black" href="{% url 'culinary_recipe:home' %}">Главное</a>
                    <i class="right chevron icon divider black"></i>
                    <a class="section navbar_links_yummy black" href="{% url 'culinary_recipe:dishes' %}">Все
                        категории</a>

                    {% block breadcrumbs %}
                    {% endblock breadcrumbs %}
                </div>
            </div>
            <hr class="mb-10">
            {% endblock steps_breadcrumbs %}

            {% block filter %}

            {% endblock filter %}
            <div class="ui stackable grid filter_element_container">

                <!-- /.blog-sidebar Каталог рецептов -->
                {% block full %}
                <div class="twelve wide fluid column content_side_yummy mx-20">
                    {% endblock full %}
                    <!-- Bread crumbs -->

                    {% block content %}
                    <hr>
                    {% endblock %}

                </div>
                {% block sidbar %}
                {% include 'includes/side_bar.html' %}
                {% endblock sidbar %}
            </div>
            {% block paginator %}
            {% endblock paginator %}

            {% block popularity %}
            {% endblock popularity %}
            <div class="advertisement">
                    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5728429283871821"
                         crossorigin="anonymous"></script>
                    <!-- √оризонтальный -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-5728429283871821"
                         data-ad-slot="3448670744"
                         data-ad-format="auto"
                         data-full-width-responsive="true"></ins>
                    <script>
                         (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
        </div>
    </div>

    {% include 'includes/footer.html' %}
    
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jqueryPassiveFix.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>

    
    <!--Semantik Ui Js-->
    <script async type="text/javascript" src="{% static 'Semantic_UI/semantic.min.js' %}"></script>
    <!--  custom js -->
    <script type="text/javascript" src="{% static 'js/masonry.pkgd.min.js' %}"></script>

    <script async type="text/javascript" src="{% static 'js/base.min.js' %}"></script>

    {% block jscdn %}

    {% endblock jscdn %}
    <script>
        {% block javascript %}
        {% endblock javascript %}
        var $grid = $('.grid_ushefa').masonry({
            fitWidth: true,
            gutter: 10,
            itemSelector: '.grid-item_ushefa',
        });
        $grid.imagesLoaded()
        .always(function () {
            $grid.masonry('layout');
        })
        .done(function () {
            $grid.masonry('layout');
        })
        .fail(function () {
            $grid.masonry('layout');
        });
    </script>
</body>

</html>

src/templates/home.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    <h1 class="ui pl-10 font-oswald">
        Кулинарные рецепты
    </h1>

    <div class="blog-post">
        <div class="ui stackable centered three column grid">

            {% for category in categories %}
            {% if forloop.last %}
            <div class="five wide column cont advertisement_yandex">
                            <!-- Yandex.RTB R-A-1494480-1 -->
                <div id="yandex_rtb_R-A-1494480-1"></div>
                    <script>window.yaContextCb.push(()=>{
                      Ya.Context.AdvManager.render({
                        renderTo: 'yandex_rtb_R-A-1494480-1',
                        blockId: 'R-A-1494480-1'
                      })
                    })</script>
            </div>
            {% endif %}
                <div class="five wide column cont">
                    <h2>
                        <a class="button_link" href="{{ category.get_absolute_url }}">
                            <span class="font-s-20 badge badge-secondary pl-10 popup_category" data-content="Все блюда категории {{ category.name }}">{{ category.name }}</span>
                        </a>
                    </h2>
                    <div class="page_image loading_gif">
                        <img src="/static/image/1x1.png" data-src="{{ category.poster.url }}" alt="{{ category.name }}" width="250px">
                    </div>
                    {% if category.sub_category.all %}
                        {% for child in category.sub_category.all %}
                            <span class="{% if forloop.counter >= 3 %}{{category.slug}}_div_container d_none{% endif %}">
                                <a class="button_link" href="{{ child.get_absolute_url }}">
                                    {{ child.name }} :
                                </a>
                                {% if child.get_last_three_dishes %}
                                {% for dishes in child.get_last_three_dishes %}
                                <a class="popup_category" href="{{ dishes.get_absolute_url }}"
                                   data-html='<img class="ui small image" src="{{ dishes.poster.url }}" alt="{{dishes.title}}">'>
                                        {{ dishes.title }}
                                </a>
                                {% endfor %}
                                {% endif %}
                            </span>
                        {% endfor %}
                        {% if category.sub_category.all.count > 3 %}
                            <div class="show_more_button" datatype="{{category.slug}}_div_container"><i class="ui small plus grey icon"></i>показать все</div>
                        {% endif %}
                    {% endif %}

                </div>
            {% endfor %}

        </div>
    </div>
        <div class="row p-10">
                <div class="justify_center">
                    <a class="link item" href="{% url 'culinary_recipe:dishes' %}">
                        <div class="ui animated fade button my_button" tabindex="0">
                            <div class="visible content">Все рецепты</div>
                            <div class="hidden content">
                                Перейти
                            </div>
                        </div>
                    </a>
                </div>
            </div>
{% endblock %}
        {% block popularity %}
         <hr>

    <h2 class="ui header pl-10 font-oswald">Кулинарные посты и новости</h2>
    <div class="grid_ushefa">
        {% for post in posts %}
            <div class="grid-item_ushefa">
                <a href="{{ post.get_absolute_url }}" class="ui fluid card">
                          <div class="page_image loading_gif">
                        <img src="/static/image/1x1.png" data-src="{{ post.image.url }}" alt="{{ post.title }}">
                          </div>
                          <div class="content">
                              <div class="header grey text_center">
                                {{ post.title }}
                              </div>
                          </div>

                    </a>

            </div>
        {% endfor %}
    </div>
        <div class="row p-10">
            <div class="justify_center">
                <a class="link item" href="{% url 'culinary_post:culinary_post_view' %}">
                    <div class="ui animated fade button my_button" tabindex="0">
                        <div class="visible content">Все посты</div>
                        <div class="hidden content">
                            Перейти
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <hr>
          <h2 class="pl-10 font-oswald">Популярные рецепты</h2>
            <div class="grid_ushefa">
            {% for popular_meal in popular_meals %}
                <div class="grid-item_ushefa">
                    <a href="{{popular_meal.get_absolute_url}}" class="ui fluid card">
                          <div class="page_image loading_gif">
                        <img src="/static/image/1x1.png" data-src="{{ popular_meal.poster.url }}" alt="{{popular_meal.title}}" height="100%">
                          </div>
                          <div class="content">
                              <div class="header grey">
                                {{popular_meal.title}}
                              </div>
                          </div>
                          <div class="extra content">
                                <span class="left floated">
                                  <i class="comment icon"></i>
                                    {{ popular_meal.get_total_comments}}
                                    <i class="eye icon"></i>
                                    {{ popular_meal.current_hit_count}}
                                    <i class="ui thumbs up icon"></i>
                                    {{ popular_meal.get_total_likes }}
                                </span>
                          </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <h3 class="pl-10 font-oswald">Национальные кухни</h3>
        <div class="country_block my-4">
            {% for country in countries %}
                <span class="flag">
                    <a class="button_link text-muted {% if forloop.first %}pl-10{% endif %}" href="{{country.get_absolute_url}}">
                        {{ country.name }}: {{country.cnt}}
                        {% if not forloop.last %},{% endif %}
                    </a>
                </span>
            {% endfor %}
        </div>
    {% endblock popularity %}
</div>