src/culinary_post/urls.py
from django.urls import path
from . import views

app_name = 'culinary_post'

urlpatterns = [
    path('', views.post__list_view, name='culinary_post_view'),
    path('detail/<int:pk>', views.CulinaryPostDetailView.as_view(), name='culinary_post_detail_view'),
    path("detail/<int:pk>/<int:number>/", views.CulinaryPostDetailView.as_view(), name='load_more_comments'),
    path('post/add_comment/<int:pk>', views.AddCommentToPost.as_view(), name='post_add_comment'),
    path('post_add/', views.posts_add, name='culinary_post_add'),
    path('liked/', views.like_unlike_post, name='like_post_view'),
    path('delete/<pk>/delete/', views.CulinaryPostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', views.CulinaryPostUpdateView.as_view(), name='post_update'),
]

src/culinary_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='text/xml')),
    path('ads.txt', TemplateView.as_view(template_name='ads.txt', content_type='text/xml')),
    path('sellers.json', TemplateView.as_view(template_name='sellers.json', content_type='text/json')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ushefa_admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('contact.urls', namespace='profile')),
    path('posts/', include('culinary_post.urls', namespace='culinary_post')),
    path('private/chat/', include('private_chat.urls', namespace='private_chat')),
    path('', include('culinary_recipe.urls', namespace='culinary_recipe')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/culinary_recipe/urls.py
from django.urls import path
from . import views


app_name = 'culinary_recipe'
urlpatterns = [
    path('', views.CategoryViewList.as_view(), name='home'),
    path('ajax/', views.get_ajax_response_category, name='get_ajax_response_category'),
    path('dishes/', views.GetItems.as_view(), name='dishes'),
    path('dishes/by_search/', views.Search.as_view(), name='search_dishes'),
    path('dishes/by_search/<int:page_num>', views.Search.as_view(), name='search_pagination'),
    path('dishes/by_search_title/', views.SearchByTitle.as_view(), name='search_dishes_by_title'),
    path('dishes/add_recipe/', views.DishCreateView.as_view(), name='add_recipe'),
    path('dishes/update_dish/<slug:slug>/', views.DishUpdateView.as_view(), name='update_meal'),
    path('dishes/delete_dish/<int:pk>/', views.DishDeleteView.as_view(), name='delete_meal'),
    path('detail/<slug:slug>/<int:pk>', views.MealDetailView.as_view(), name='detail_view'),
    path("detail/<str:slug>/<int:pk>/<int:number>/", views.MealDetailView.as_view(), name='load_more_comments'),
    path('review/<int:pk>/', views.AddCommentToDish.as_view(), name='add_review'),
    path('recipe/dishes/<slug:slug>/', views.GetItems.as_view(), name='last_list'),
    path('likes_meal/', views.like_unlike_post, name='likes_meal'),
    path('json/', views.ingredient_list_view, name='get_ingredient_lists'),
    path('category/country/<slug:country>/<int:pk>', views.GetItems.as_view(), name='by_country'),
    path('<slug:slug>/', views.get_sub_category, name='cats_list'),
]

src/templates/includes/header.html
{% load static %}
{% load meal_tags %}
{% load notification_tags %}

{% if user.is_authenticated %}
{% all_notification user.profile.id as notification %}
{% new_messages_not user.profile.id as msg_notification %}
{% endif%}
<div id="navbar" class="ui top fixed inverted menu navbar_yummy asr" style="display: block !important;">
    <div class="ui container first_nav_block" style="display: flex !important;">
        <div class="item"><i class="big white bars icon"></i></div>
        <div class=" navbar_menu_container" style="display: flex !important;">
            <div class="item">
                <a href="/" class="mr-10">
                    <img loading="lazy" src="/static/image/logo_header.png" alt="">
                </a>
            </div>
            <div class="item"><a class="p-2 navbar_links_yummy font-oswald"
                                 href="{% url 'culinary_post:culinary_post_view' %}">Кулинарные посты</a></div>
        </div>
        <div class="right menu">

                <div class="item">
                    <i class="big white search link icon search_form_ushefa_icon display aaa"></i>
                    <form action="{% url 'culinary_recipe:search_dishes_by_title' %}"
                          class="ui icon input mr-10 search_form_ushefa display" method="get">
                        <div class="ui action input">
                            <input class=" font-oswald" type="search" placeholder="Введите слово" aria-label="Search"
                                   name="q">
                            <button class="ui basic yellow button" type="submit">
                                <i class="search link icon"></i>
                            </button>
                        </div>
                    </form>
                    <div class="add_dropdown_box_button_ushefa top ui floating labeled icon dropdown menu basic yellow button"
                         tabindex="0">
                        <i class="add icon add_dropdown_icon_ushefa"></i>
                        <span class="text add_more_text_ushefa">Добавить</span>
                        <div class="menu bgc transition hidden add_post_box_custom" tabindex="-1">
                            <div class="item">
                                <div class="ui buttons">
                                    <a href="{% url 'culinary_post:culinary_post_add' %}" class="ui button add_post_icon">
                                        Пост
                                    </a>
                                    <a href="{% url 'culinary_recipe:add_recipe' %}" class="ui button add_recipe_icon">
                                        Рецепт
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% if user.is_authenticated %}
                <div class="item centered_custom top">
                    <span class="notification_number {% if notification > 0 %}visible{% endif %}"><small>{{ notification }}</small></span>
                    <div class="ui right pointing scrolling dropdown user_post" tabindex="0">
                        <img loading="lazy" class="ui img-container avatar image"
                             src="{% if user.profile.avatar %}{{ user.profile.avatar.url }}{% else %}/static/image/avatar_man.png{% endif %}"
                             alt="avatar">
                        <span class="text white">{{user.profile.first_name}}</span>
                        <div class="menu transition hidden add_post_box_custom" tabindex="-1">
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10"
                                   href="{{ user.profile.get_personal_absolute_url }}" >
                                <i class="file outline icon"></i>Ваша страница
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:my_invites_view' %}">
                                <i class="user outline icon"></i>
                                Запрос на
                                    дружбу
                                    <span class="ui red label ">{{ user.profile.get_total_friend_request }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10"
                                   href="{{user.profile.get_absolute_url_for_friends_view}}">
                                <i class="chat outline icon custom_chat_icon"></i>
                                Сообщения
                                    <span class="ui red label ">{{ msg_notification }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:all_profiles_view' %}">
                                <i class="users icon"></i>
                                Все пользователи
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:invite_profiles_view' %}">
                                <i class="search icon"></i>
                                Найти друзей
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{{ user.profile.get_dish_book_absolute_url }}">
                                <i class="book icon"></i>Кулинарная книга
                                <span class="ui teal label dish_book_count">{{ user.profile.get_total_book }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'account_logout' %}">
                                <i class="logout icon"></i> Выйти
                            </a>

                        </div>
                    </div>
                </div>
                {% else %}
                <div class="item centered_custom top">
                    <i class="user big white icon img-container"></i>
                    <a class="p-2 text-dark" href="{% url 'account_login' %}">
                        <div class="text white">Войти</div>
                    </a>
                </div>
                {% endif %}
            </div>
    </div>
    <div class="ui container second_nav_block">
            <div class="item p-0">
                <a href="/" class="mr-10">
                    <img loading="lazy" src="/static/image/logo_header.png" alt="">
                </a>
            </div>

            <div class="right menu">
                {% if user.is_authenticated %}
                <div class="item centered_custom">
                    <span class="notification_number {% if notification > 0 %}visible{% endif %}"><small>{{ notification }}</small></span>
                    <div class="user_post ui top right pointing scrolling dropdown user_post" tabindex="0">
                        <img loading="lazy"  class="ui img-container avatar image"
                             src="{% if user.profile.avatar %}{{ user.profile.avatar.url }}{% else %}/static/image/avatar_man.png{% endif %}"
                             alt="avatar">
                        <span class="text white">{{user.profile.first_name}}</span>

                        <div class="menu transition hidden add_post_box_custom" tabindex="-1">
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10"
                                   href="{{ user.profile.get_personal_absolute_url }}" >
                                <i class="file outline icon"></i>Ваша страница
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:my_invites_view' %}">
                                <i class="user outline icon"></i>
                                Запрос на
                                    дружбу
                                    <span class="ui red label ">{{ user.profile.get_total_friend_request }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10"
                                   href="{{user.profile.get_absolute_url_for_friends_view}}">
                                <i class="chat outline icon custom_chat_icon"></i>
                                Сообщения
                                    <span class="ui red label ">{{ msg_notification }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:all_profiles_view' %}">
                                <i class="users icon"></i>
                                Все пользователи
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'contact:invite_profiles_view' %}">
                                <i class="search icon"></i>
                                Найти друзей
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{{ user.profile.get_dish_book_absolute_url }}">
                                <i class="book icon"></i>Кулинарная книга
                                <span class="ui teal label dish_book_count">{{ user.profile.get_total_book }}</span>
                            </a>
                            <div class="divider"></div>
                            <a class="item font-yanone black pt-10" href="{% url 'account_logout' %}">
                                <i class="logout icon"></i> Выйти
                            </a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="item centered_custom">
                    <i class="user big white icon img-container"></i>
                    <a class="p-2 text-dark" href="{% url 'account_login' %}">
                        <div class="text white">Войти</div>
                    </a>
                </div>
                {% endif %}
                <div class="item centered_custom">
                    <div class="ui top right pointing dropdown " tabindex="0">
                        <i class="add icon img_container big" style="display: block !important; margin: auto !important;"></i>
                        <span class="text white">Добавить</span>
                        <div class="menu bgc transition hidden add_post_box_custom" tabindex="-1">
                            <div class="item">
                                <div class="ui buttons">
                                    <a href="{% url 'culinary_post:culinary_post_add' %}" class="ui button add_post_icon">
                                        Пост
                                    </a>
                                    <a href="{% url 'culinary_recipe:add_recipe' %}" class="ui button add_recipe_icon">
                                        Рецепт
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

src/templates/includes/notification.html
{% extends 'base.html' %}

{% block content %}
<div class="ui yellow message text_center">
    {{ notification }} <br>
    <a href="/">Вернутся на главную</a><br>
    {% if link_to_back %}
    <a href="{{ link_to_back }}">Вернутся на на страницу</a>
    {% endif %}
</div>


{% endblock content %}

src/templates/includes/pagination.html
<div class="ui centered pagination menu mb-10 pagination_try">
    {% if page_obj.has_previous %}
    <a href="?{{q}}page={{ page_obj.previous_page_number }}" class="icon item"><i class="left chevron icon"></i></a>
    {% if page_obj.number|add:'-3' > 1 %}
    <a href="?{{q}}page=1" class="item">1</a>
    {% endif %}
    {% if page_obj.number|add:'-2' >= 2 %}
        <a href="?{{q}}page={{ page_obj.previous_page_number|add:'-2' }}" class="item">...</a>
    {% endif %}
    {% endif %}
    {% if page_obj.paginator.page_range|length > 1 %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <span class="active item">{{i}}</span>
            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                <a href="?{{q}}page={{ i }}" class="item">{{ i }}</a>
            {% endif %}
        {% endfor %}
    {% endif %}
{% if page_obj.has_next %}
    {% if page_obj.number|add:'2' < page_obj.paginator.num_pages %}
        <a href="?{{q}}page={{ page_obj.next_page_number|add:'2' }}" class="item">...</a>
    {% endif %}
    {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
        <a href="?{{q}}page={{ page_obj.paginator.num_pages }}" class="item">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
    {% if page_obj.number < page_obj.paginator.num_pages %}
        <a href="?{{q}}page={{ page_obj.next_page_number }}" class="icon item"><i class="right chevron icon"></i></a>
    {% endif %}
{% endif %}
</div>

src/templates/includes/side_bar.html
{% load meal_tags %}
{% load static %}

<div class="four wide column">
    <!-- Yandex.RTB R-A-1494480-2 -->
        <div id="yandex_rtb_R-A-1494480-2"></div>
        <script>window.yaContextCb.push(()=>{
          Ya.Context.AdvManager.render({
            renderTo: 'yandex_rtb_R-A-1494480-2',
            blockId: 'R-A-1494480-2'
          })
        })</script>
    {% get_last_dishes %}
    {% get_categories as categories %}
    <div class="ui vertical fluid menu category_side_yummy">
        <div class="font-s-25 font-italic font-lobster p-10">Категории</div>
        <div class="ui accordion">
            {% for category in categories %}
            {% if category.sub_category.all %}
            <div class="title">
                <i class="dropdown icon"></i>
                <a href="{{ category.get_absolute_url }}" class="navbar_links_yummy font-oswald font-oswald black">
                    {{ category.name }}
                </a>
            </div>
            <div class="middle aligned content" id="{{ category.slug }}">
                {% for sub_category in category.sub_category.all %}
                <p class="accordion transition visible" style="display: block !important;">
                    <a href="{{ sub_category.get_absolute_url }}"
                       class="navbar_links_yummy font-oswald font-oswald black pl-20">
                        {{sub_category.name}} : {{ sub_category.dish_set.all.count }}
                    </a>
                </p>
                {% endfor %}
            </div>
            {% else %}
            <a href="{{ category.get_absolute_url }}" class="navbar_links_yummy font-oswald font-oswald black pl-10">
                {{ category.name }}
            </a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
<!--    Рекламный блок-->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5728429283871821"
                     crossorigin="anonymous"></script>
                <!-- Реклама -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-5728429283871821"
                     data-ad-slot="9657311282"
                     data-ad-format="auto"
                     data-full-width-responsive="true"></ins>
                <script>
                     (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
</div>